Webapp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Webapp.Data.Account;

namespace Webapp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<User> _signInManager;
        public AccountController(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }
        public async Task<IActionResult> ExternalLoginCallback()
        {
            var loginInfo = await _signInManager.GetExternalLoginInfoAsync();
            var emailClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            var userClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            if (emailClaim != null && userClaim != null)
            {
                var user = new User { Email = emailClaim.Value, UserName = userClaim.Value };
                await _signInManager.SignInAsync(user, false);
            }

            return RedirectToPage("/Index");
        }
    }
}

Webapp/Pages/Account/AuthenticatorWithMFASetup.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using Webapp.Data.Account;

namespace Webapp.Pages.Account
{
    [Authorize]
    public class AuthenticatorWithMFASetupModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        [BindProperty]
        public SetupMFAViewModel ViewModel { get; set; }
        [BindProperty]
        public bool Succeded { get; set; }
        public AuthenticatorWithMFASetupModel(UserManager<User> userManager)
        {
            _userManager = userManager;
            ViewModel = new SetupMFAViewModel();
        }
        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(base.User);
            await _userManager.ResetAuthenticatorKeyAsync(user);
            var key = await _userManager.GetAuthenticatorKeyAsync(user);
            ViewModel.Key = key;
            ViewModel.QRCodeBytes = GenerateQRCodeBytes(_userManager.Options.Tokens.AuthenticatorTokenProvider, key, user.Email);
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();
            var user = await _userManager.GetUserAsync(base.User);
            var verified = await _userManager.VerifyTwoFactorTokenAsync(user,
                _userManager.Options.Tokens.AuthenticatorTokenProvider, ViewModel.SecuretyCode);
            if (verified)
            {
                Succeded = true;
            }
            else
            {
                ModelState.AddModelError("AuthenticatorSetup","Some thing went wrong with authenticator setup.");
            }
            return Page();
        }
        private Byte[] GenerateQRCodeBytes(string provider, string key, string userEmail)
        {
            var qrCodeGenerater = new QRCodeGenerator();
            var qrCodeData = qrCodeGenerater.CreateQrCode(
                $"otpauth://totp/{provider}:{userEmail}?secret={key}&issuer={provider}",
                QRCodeGenerator.ECCLevel.Q);
            var qrCode = new QRCode(qrCodeData);
            var qrCodeImage = qrCode.GetGraphic(20);

            return BitmapToByteArray(qrCodeImage);
        }

        private Byte[] BitmapToByteArray(Bitmap image)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                image.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }

    public class SetupMFAViewModel
    {
        public string Key { get; set; }
        [Required]
        [Display(Name = "Code")]
        public string SecuretyCode { get; set; }
        public Byte[] QRCodeBytes { get; set; }
    }
}

Webapp/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Webapp.Data.Account;

namespace Webapp.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        public ConfirmEmailModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        [BindProperty]
        public string Message { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId,string token)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var emailConfirm = await _userManager.ConfirmEmailAsync(user, token);
                if (emailConfirm.Succeeded)
                {
                    Message = "Email address is successully confirmed, now you can try to login.";
                    return Page();
                }
            }
              Message = "Failed to validate email.";
              return Page();
            
        }
    }
}

Webapp/Pages/Account/Login.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Webapp.Data.Account;

namespace Webapp.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public CredentialViewModel Credential { get; set; }

        [BindProperty]
        public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; }
        public LoginModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }
        public async Task OnGet()
        {
            ExternalLoginProviders= await _signInManager.GetExternalAuthenticationSchemesAsync();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();
            var result = await _signInManager.PasswordSignInAsync(Credential.Email, Credential.Password, Credential.RememberMe, false);
            if (result.Succeeded) { return RedirectToPage("/Index"); }
            else
            {
                if (result.RequiresTwoFactor)
                {
                    //return RedirectToPage("/Account/LoginTwoFactor", new { Email = Credential.Email, RememberMe = Credential.RememberMe });
                    return RedirectToPage("/Account/LoginTwoFactorWithAuthenticator", new { RememberMe = Credential.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login", "User is locked out");
                }
                else
                {
                    ModelState.AddModelError("Login", "Failed to login");
                }
            }

            return Page();
        }
        public IActionResult OnPostLoginExternally(string provider)
        {
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, null);
            properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

            return Challenge(properties, provider);
        }
    }
    public class CredentialViewModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remeber Me")]
        public bool RememberMe { get; set; }
    }
}

Webapp/Pages/Account/LoginTwoFactor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Webapp.Data.Account;
using Webapp.Services;

namespace Webapp.Pages.Account
{
    public class LoginTwoFactorModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly IEmailService _emailService;
        [BindProperty]
        public TwoFactorLogin TwoFactorLogin { get; set; }
        public LoginTwoFactorModel(UserManager<User> userManager,IEmailService emailService,SignInManager<User>signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _emailService = emailService;
            TwoFactorLogin = new();
        }
        public async Task OnGetAsync(string email,bool rememberMe)
        {
            var user = await userManager.FindByEmailAsync(email);
            var token = await userManager.GenerateTwoFactorTokenAsync(user, "Email");
            TwoFactorLogin.RememberMe = rememberMe;
            await _emailService.SendAsync("sachindewan12@gmail.com", "sachindewan12@gmail.com",
                "Two factor authentication",
                $"please verify the two factor authentication for successful login {token}");
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var result = await signInManager.TwoFactorSignInAsync("Email",TwoFactorLogin.MFAToken,TwoFactorLogin.RememberMe,false);
            if (result.Succeeded) { return RedirectToPage("/Index"); }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login2FA", "User is locked out");
                }
                else
                {
                    ModelState.AddModelError("Login2FA", "Failed to login");
                }
            }

            return Page();
        }
    }

    public class TwoFactorLogin
    {
        public string MFAToken { get; set; }
        public bool RememberMe { get; set; }
    }
}

Webapp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Webapp.Data.Account;

namespace Webapp.Pages.Account
{
    public class LoginTwoFactorWithAuthenticatorModel : PageModel
    {
        [BindProperty]
        public AuthenticatorMFA AuthenticatorMfa { get; set; }

        private readonly SignInManager<User> _signInManager;

        public LoginTwoFactorWithAuthenticatorModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
            AuthenticatorMfa = new AuthenticatorMFA();
        }
        public void OnGet(bool rememberMe)
        {
            AuthenticatorMfa.RememberMe = rememberMe;
            AuthenticatorMfa.SecurityCode = string.Empty;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();
            var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(AuthenticatorMfa.SecurityCode,
                AuthenticatorMfa.RememberMe, false);
            if (result.Succeeded) { return RedirectToPage("/Index"); }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Authenticator2FA", "User is locked out");
                }
                else
                {
                    ModelState.AddModelError("Authenticator2FA", "Failed to login");
                }
            }

            return Page();
        }
    }

    public class AuthenticatorMFA
    {
        [Required]
        [Display(Name = "Code")]
        public string SecurityCode { get; set; }

        public bool RememberMe { get; set; }
    }
}

Webapp/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Webapp.Data.Account;

namespace Webapp.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        public LogoutModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        } 
        public async Task<IActionResult> OnPostAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Index");
        }
    }
}

Webapp/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Webapp.Data.Account;
using Webapp.Services;

namespace Webapp.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IEmailService _emailService;
        [BindProperty]
        public RegisterViewModel RegisterViewModel { get; set; }
        public RegisterModel(UserManager<User> userManager, IEmailService emailService)
        {
            _userManager = userManager;
            _emailService = emailService;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();
            // Validating Email address (Optional)

            // Create the user 
            var user = new User
            {
                Email = RegisterViewModel.Email,
                UserName = RegisterViewModel.Email,
                Department = RegisterViewModel.Department,
                Position = RegisterViewModel.Position,
                TwoFactorEnabled = true
            };
            var result = await _userManager.CreateAsync(user, RegisterViewModel.Password);
            if (result.Succeeded)
            {
                var claimDepartment = new Claim("Department", RegisterViewModel.Department);
                var claimPosition = new Claim("Position", RegisterViewModel.Position);
                await _userManager.AddClaimAsync(user, claimDepartment);
                await _userManager.AddClaimAsync(user, claimPosition);
                //var emailConfirmationtoken = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                //var confirmationLink = Url.PageLink(pageName: "/Account/ConfirmEmail", values: new { userId = user.Id, token = "emailConfirmationtoken" });
                //await _emailService.SendAsync("sachindewan12@gmail.com", user.Email
                //    , "Please confirm your mail."
                //    , $"<b>please click on this link to confirm your mail address</b> <br> {confirmationLink}");
                return RedirectToPage("/Account/Login");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("Register", error.Description);
                }

                return Page();
            }
        }
    }
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        public string Email { get; set; }

        [Required]
        [DataType(dataType: DataType.Password)]
        public string Password { get; set; }
        [Required]
        public string Department { get; set; }
        [Required]
        public string Position { get; set; }
    }
}

Webapp/Pages/Account/AuthenticatorWithMFASetup.cshtml
@page
@model Webapp.Pages.Account.AuthenticatorWithMFASetupModel
@{
}

<h3>Step 1:</h3>
<p>
    Please scan the QR Code or enter the key to your authenticator app:    
</p>
<p>
    <img src="@string.Format("data:image/png;base64,{0}", 
                  @Convert.ToBase64String(Model.ViewModel.QRCodeBytes))" 
         width="300" 
         height="300"/>
</p>
<br />
<p>
    @Model.ViewModel.Key
</p>
<h3>Step 2:</h3>
<p>Please enter the code from your authenticator app:</p>
<div class="container border" style="padding:20px">
    <form method="post">
        @if (@Model.Succeded)
        {
            <div class="alert alert-success">
                The authenticator is successfully setup.
            </div>
        }
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ViewModel.SecuretyCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="ViewModel.SecuretyCode" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="ViewModel.SecuretyCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify"/>
            </div>
            <div class="col">
                <input type="hidden" asp-for="ViewModel.Key"/>
                <input type="hidden" asp-for="ViewModel.QRCodeBytes"/>
            </div>
        </div>
    </form>
</div>

Webapp/Pages/Account/ConfirmEmail.cshtml
@page
@model Webapp.Pages.Account.ConfirmEmailModel
@{
}

<p>
    @Model.Message
</p>

Webapp/Pages/Account/Login.cshtml
@page
@model Webapp.Pages.Account.LoginModel
@{
}
<p>
    <h3>User Login</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Credential.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="Credential.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Password"></span>
        </div>
        <div class="row form-check mb-2">
            <div class="col-2">
                <input type="checkbox" asp-for="Credential.RememberMe" class="form-check-input" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col">

            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col">
                <a class="btn btn-link" href="/Account/Register">Sign Up</a>
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach(var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit"
                            asp-page-handler="LoginExternally"
                            name="provider"
                            value="@provider.Name"
                            class="btn btn-primary"
                    >
                        Login with @provider.DisplayName
                    </button>
                            
                }
            </div>
        </p>
    </form>
</div>

Webapp/Pages/Account/LoginTwoFactor.cshtml
@page
@model Webapp.Pages.Account.LoginTwoFactorModel
@{
}
<p>
    <h3>please enter the code from your email.</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="TwoFactorLogin.MFAToken"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="TwoFactorLogin.MFAToken" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="TwoFactorLogin.MFAToken"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="TwoFactorLogin.RememberMe"/>
            </div>
        </div>
    </form>
</div>

Webapp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml
@page
@model Webapp.Pages.Account.LoginTwoFactorWithAuthenticatorModel
@{
}
<p>
    <h3>please enter the code from your authenticator app.</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="AuthenticatorMfa.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="AuthenticatorMfa.SecurityCode" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="AuthenticatorMfa.SecurityCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="AuthenticatorMfa.SecurityCode" />
            </div>
        </div>
    </form>
</div>

Webapp/Pages/Account/Logout.cshtml
@page
@model Webapp.Pages.Account.LogoutModel
@{
}
<span>Logged out successfully..please login again to proceed further</span>

Webapp/Pages/Account/Register.cshtml
@page
@model Webapp.Pages.Account.RegisterModel
@{
}
<p>
    <h3>User Registration</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Department"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Department" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Department"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Position"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Position" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Position"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="RegisterViewModel.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Password"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
            <div class="col">

            </div>
        </div>
    </form>
</div>


Webapp/Pages/Account/UserProfile.cshtml
@page
@model Webapp.Pages.Account.UserProfileModel
@{
}
<p>
    <h3>User Profile</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="UserProfile.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="UserProfile.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="UserProfile.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="UserProfile.Department"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="UserProfile.Department" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="UserProfile.Department"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="UserProfile.Position"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="UserProfile.Position" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="UserProfile.Position"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
            <div class="col">

            </div>
        </div>
    </form>
</div>
@if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
{
    <div>
        @Model.SuccessMessage
    </div>
}
